### ISSUE TITLE
Upload to Cloudinary by default.

### ISSUE THREAD

**Issue by malchata** [cloudinary/cloudinary_wordpress#12]
Hello. First off, Cloudinary is pretty awesome, and this WordPress plugin is great, too!

I was wondering if there was a way to set up this plugin so that images are uploaded to Cloudinary by default. The current workflow has me uploading an image through an Advanced Custom Fields post, then having to manually kick off a migration to Cloudinary for each new image I upload. For me personally, this isn't so bad, but I work for a company where we have content authors that aren't going to think to do this every time they upload images.

Other than this small bump in the road, I'm really impressed by this service and this plugin.

-j

**Comment by roeeba** [comment]
Hi, @malchata. Thanks for the great feedback! :)

In regards to your question, Cloudinary doesn't currently support automatic uploads. Note that you can import your images in bulk via your WP 'Media' tab. Hope this helps.

**Comment by malchata** [comment]
Hi, @roeeba! Thanks for getting back to me.

Bummer! I was hoping maybe there would be a way to automate uploads, but no dice. I did notice the bulk import capability, which does help quite a bit. All in all, this is a great tool for a great service!

I'll go ahead and close the issue.
