### ISSUE TITLE
Overflow hidden in midia library navigation

### ISSUE THREAD

**Issue by CesarRiello** [cloudinary/cloudinary_wordpress#13]
I can not navigate through folders or through the list of images in the media library. Even opening the iframe src (https: //cloudinary.com/console/media_library/cms? timestamp = 1510861923 & mode = wp_gallery & plugin_version = 1.1.6 & signature = ...)

Inspecting, I can see that:

```
#wrapper {
    position: relative;
    overflow: hidden; <<<<
}
```

**Comment by roeeba** [comment]
Hi @CesarRiello. A fix had been deployed. Thank you very much for reporting this.
