### ISSUE TITLE
Media won't load up in Media Library

### ISSUE THREAD

**Issue by 4tstar** [cloudinary/cloudinary_wordpress#149]
The plugin seems to be currently in beta since there are as many bugs. These are :
1) In 2.1.0 plugin, Admin panel Media Library working fine and wp media library images are also visible and load but in 2.2.0 no images load or displayed in Media Library.
![Screenshot_2020-08-03-10-35-18-085_com android chrome](https://user-images.githubusercontent.com/67037053/89149055-1fd47d80-d579-11ea-95ec-4188cfafa8dc.jpg)

2) after performing the Bulk Sync, it displayed all media are synced but many images are yet not sync and no matter what you do, it won't sync. Due to this images on post won't displayed when user visited. 

3) seems little bit unstable differ images are attached to differ post.

4) some issues with classic-editor.

I'm a big fan of Cloudinary and when I see wp plugin, feel quite amazed but it won't work at last disappoint me. Please make.it happen, make it stable 💯 Thanks ❤

**Comment by leptians** [comment]
Hi @4tstar ,

Thank your for reporting this.
I would like to clarify a few things with you on this.
Our plugin is currently up to version 2.1.2 and never released version 2.1.0 to Wordpress marketplace. Can you confirm the version that you were/are using, v2.1.0 and 2.2.0? Can you also let me know where did you download the plugin from?

Additionally, can you please share the list of installed and activated plugin along with Wordpress version?

Looking forward to your response.

Regards,
Erwin Lukas

**Comment by 4tstar** [comment]
Ah sorry, I'm using 2.1.2 and Push Images to Cloudinary manually in media Library. So, sync worked the other way. but Media won't show up as shown in above screenshot in media Library. Then I uninstalled latest version and then install v2.1.1 in which media library load images and appears fine.
So, finally there is only problem of images not load or appears in media Library in the latest version. See screenshot above for reference. Thanks !

**Comment by Vdeub-cloudinary** [comment]
Hi @4tstar ,

Thanks for the information provided.
Can you try to display the images as a list view and not as a grid view? And let us know if the images still do not appear?

Can you also share a list of installed and activated plugins?

Thanks in advance.
Best,
Loic

**Comment by 4tstar** [comment]
Yep, list view works !
I don't use any plugins. It's just classic editor.

**Comment by leptians** [comment]
Hi @4tstar, 

Are you saying the list view shows the image but not on the grid mode?

Regards,
Erwin Lukas

**Comment by 4tstar** [comment]
Yes !

**Comment by leptians** [comment]
@4tstar ,

Both grid mode and list mode are using the same URL, so it should behave the same manner.
Are you also able to reproduce this with other browser? From the screenshot above, seems like you are using chromium based mobile browser on Android.Can you test this on a computer as well?
If it's reproducible on all browsers, for us to investigate more and if it is ok with you, can you please open a ticket on [our portal](https://support.cloudinary.com/hc/en-us/requests/new) since we will be asking some information regarding your account?

Regards,
Erwin Lukas
