### ISSUE TITLE
Feature request: Support multisite

### ISSUE THREAD

**Issue by soderlind** [cloudinary/cloudinary_wordpress#156]
My user stories for this feature request would be something like:

> As a super admin I network activates the plugin, and, in the network admin dashboard, I add my Cloudinary access key. 
Each subsite gets its own cloudinary folder path ( = subsite folder name ?). 
In network admin I set the global transformations and sync settings for all subsites.

> As an admin / editor on a subsite, I can only add and view images in my subsite cloudinary folder path.

Business case: I have 100+ subsites, and 300+ GB of images.

**Comment by leptians** [comment]
Hi @soderlind ,

Thank you for reaching out.
Let me check regarding multisite functionalities with the internal team.

Regarding the usage, we don't have any limit regarding number of folders (1 folder per site).
In order on how we calculate our usage, please check our [pricing page](https://cloudinary.com/pricing).
If you want to learn more or have any detail questions, I would recommend to open a ticket from our [Support Portal](https://support.cloudinary.com/hc/en-us/requests/new).

Regards,
Erwin Lukas

**Comment by soderlind** [comment]
@leptians I never got an answer to my [user story](https://github.com/cloudinary/cloudinary_wordpress/issues/156#issue-676826650).  With the latest version, I understand I can add my access key using `define( 'CLOUDINARY_CONNECTION_STRING', 'cloudinary://key:secret@cloudname' );` 

Are there [any hooks](https://cloudinary.github.io/cloudinary_wordpress/) I can use to force a per site group/flag/directory so `"As an admin / editor on a subsite, I can only add and view images in my subsite cloudinary folder path."` ?

**Comment by wissam-khalili** [comment]
Hi @soderlind , Thank you for your input.
Please note that this option is not available for the moment, although it is planned in our product roadmap.
Thanks,
Wissam

**Comment by soderlind** [comment]
@wissam-khalili Was this added to the latest release?

**Comment by wissam-khalili** [comment]
Hi @soderlind , 
Unfortunately, this was not added in the latest version 3.0.1.
Thanks,
Wissam
