### ISSUE TITLE
Wordpress plugin out of date on Wordpress Plugin store

### ISSUE THREAD

**Issue by grantkemp** [cloudinary/cloudinary_wordpress#2]
Currently the plugin on Wordpress is only listed as being compatible with an older version of Wordpress: 

> Requires: 3.0 or higher
> Compatible up to: 4.0.10
> Last Updated: 1 year ago
> Active Installs: 3,000+

Link: https://wordpress.org/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/
We have some customers that want to use it - can you update the Wordpress plugin site. 

Specifically we would like this to work on 4.41 version of wordpress.

**Comment by roeeba** [comment]
Hi @grantkemp , It's on our road-map to support additional features on future WordPress versions.
In the meantime, the current plugin's features are still fully working, lately tested on version 4.5.2.
If there's any issue that you are experiencing, please let us know.

**Comment by michaelBenin** [comment]
Anyone test this on 4.6.1?

**Comment by michaelBenin** [comment]
Never mind. https://github.com/cloudinary/cloudinary_wordpress/pull/5

**Comment by lukecav** [comment]
Version on SVN shows 4.7
https://plugins.svn.wordpress.org/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/trunk/readme.txt

Version on the Repo shows 4.0
https://github.com/cloudinary/cloudinary_wordpress/blob/master/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/readme.txt#L5
