### ISSUE TITLE
Feature request: Use only for image selection

### ISSUE THREAD

**Issue by markrzen** [cloudinary/cloudinary_wordpress#251]
Howdy! I was curious if there was either a current way or interest in a pull request, allowing the plugin to be used only for the image selection portion?

For clarity, we have a Wordpress site which uses an asset library that we manage mutations for in another way. We do not want to allow Wordpress to upload/mutate these assets, and thus we just want to use the brilliant read functionality.

Thanks in advance for response

**Comment by jayakhtar** [comment]
Hi @markrzen Thanks for reaching out.

Can you please share more details on this? You have mentioned not using WordPress for uploading or transforming images to Cloudinary? What does it mean when you say "just want to use the brilliant read functionality"? It would be helpful to get more clarity on this with an example.

Best regards,
Jay

**Comment by markrzen** [comment]
Hey @jayakhtar!

What I was hoping for is a way to make the plugin read only.

We share a design library of images between multiple applications. To keep everything in sync and cached well, we would not want Wordpress to have write access to this part of our Cloudinary file system. We would want to allow Wordpress to select from the existing images in our file system though.

Does that clarify my ask?

Thanks
Mark

**Comment by jayakhtar** [comment]
@markrzen If I understand the question correctly, you do not want Cloudinary to apply any changes or transformations to the uploaded assets, rather just serve them directly?

As long as the Global transformations are not set within the plugin settings. Cloudinary will not apply any transformation changes to the assets. For eg., keep the **Image format** and **Quality** settings to _Not Set_ in the plugin and leave the **Image Transformation String** field empty. 

Also, make sure there are no transformations added in the default Upload presets within the linked Cloudinary account.

Let me know if this helps.

Best regards,
Jay

**Comment by markrzen** [comment]
@jayakhtar I am asking for slightly different.

I want the wordpress plugin to ONLY read from Cloudinary and never write to.

**Comment by jayakhtar** [comment]
@markrzen I am checking this internally and will get back to you.

**Comment by jayakhtar** [comment]
@markrzen I just got a word back from the team, this is not supported at present and is not a straight-forward PR to make.

**Comment by markrzen** [comment]
@jayakhtar Thanks for checking for me. Sounds like I will have to figure out a different solution.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com, or create a new ticket if you have any additional issues.
