### ISSUE TITLE
1000 items per itteration seems like too many

### ISSUE THREAD

**Issue by pattonwebz** [cloudinary/cloudinary_wordpress#281]
In testing uploading a large library of images and some videos I have found that the process becomes unresponsive. The site has a significant amount of memory, CPU and bandwidth available.

I would like a filter to exist to reduce the number of items per itteration to a number I am more comfortable with on the initial production push.

https://github.com/cloudinary/cloudinary_wordpress/blob/31a7ce2510cd8fc3e6b459283648f40075a5fc27/php/sync/class-sync-queue.php#L255

**Comment by Vdeub-cloudinary** [comment]
Hi @pattonwebz, I am closing this issue as it has been solved in the ticket 137946 you raised
