### ISSUE TITLE
Option to keep the media's original filename

### ISSUE THREAD

**Issue by obedparla** [cloudinary/cloudinary_wordpress#30]
Having a "settings" panel would be great, an important functionality that is lost by using the Wordpress plugin is keeping the original's media filename as seen here: https://support.cloudinary.com/hc/en-us/articles/202520762-How-to-upload-images-while-keeping-their-original-filenames-

**Comment by idobarnoam** [comment]
Hi @obedparla it's possible to use the original file name when uploading by changing that setting on the account's [upload tab](https://cloudinary.com/console/settings/upload).

Regarding the settings - All of the account's settings that are configured on your account are relevant to uploaded resources from WP. What settings would you have wanted to have more control on from WP?

**Comment by obedparla** [comment]
That's great stuff, thank you @idobarnoam. Not sure if that's pointed in the documentation but it would be useful to know.
