### ISSUE TITLE
Way to get PDF files to sync?

### ISSUE THREAD

**Issue by apersky** [cloudinary/cloudinary_wordpress#361]
I am using version 2.6.0 of the plugin, on WordPress 5.6.1 and I am unable to get any PDF files to upload into Cloudinary. I have tried the auto-sync feature as well as the manual push to Cloudinary options. When doing bulk uploads, PDFs are just skipped, and when manually pushing one PDF at a time, you can see in the Media Library the orange sync in progress icon, but it soon on page refresh will show it is not synced.

I can not see any plugin settings or logs to show what is happening behind the scenes, so are there any filters made available, or is there some sort of setup on the Cloudinary account itself that needs to take place to allow PDFs to sync from this plugin? This link shows PDFs are allowed, so I would assume I should be able to upload via the plugin as well. Thanks.

https://cloudinary.com/documentation/image_transformations#supported_image_formats

**Comment by aksjoshi1** [comment]
Hi there,

Based on a recent update to our security policies, we've restricted the ability of new free accounts to deliver PDFs and Archive files like .zip or .rar. It's possible to upload and manage those files, and you can download them using our Media Library, but a restriction applies to deliver them publicly and you'll see an HTTP 404 error in that case.

For PDFs that are uploaded as `resource_type: 'image'`, it's possible to use those PDFs with our transformations features, so you can [convert the PDFs to another image format and deliver them that way](https://cloudinary.com/documentation/paged_and_layered_media#deliver_a_selected_pdf_page_as_an_image), such as by using the `page` transformation (`pg_` in URLs) and setting the extension to an image format like `jpg`: https://res.cloudinary.com/demo/image/upload/pg_1/multi_page_pdf.jpg

Would you mind opening a support ticket? We can control and lift this restriction from specific accounts, but we also need to ensure that no malicious files are distributed through our service. If you'd like this restriction removed, may I please ask you to share some details regarding the expected usage and origin of the PDFs and/or Archives that you'll be uploading and delivering?

In particular, please let us know who will be uploading these files, what the files contain, and whether you're generating the files yourself prior to uploading to Cloudinary or if they're provided by your users?

Looking forward to your response.

Regards,
Akshay
