### ISSUE TITLE
Incorrect call to WP get_post_meta() when $key is null

### ISSUE THREAD

**Issue by KevinBerkhof** [cloudinary/cloudinary_wordpress#405]
Since latest release we're facing a bug that is caused due to a mismatch between types.
Its about the call in `Media::get_post_meta` on
https://github.com/cloudinary/cloudinary_wordpress/blob/2.7.0/php/class-media.php#L1786

It can be possible that `$key === null` although the Wordpress `get_post_meta` expects `$key` to be a `string`  (See https://developer.wordpress.org/reference/functions/get_post_meta/)

This happens to some calls from `Sync` where `$key` is not defined and therefore set to `null` (e.g. https://github.com/cloudinary/cloudinary_wordpress/blob/2.7.0/php/class-sync.php#L482)

In the end this is for me causing issues when you use the Wordpress `get_post_metadata` filter and expect `$key` to be a string. We noticed this when using the plugin WP-GraphQL:  https://github.com/wp-graphql/wp-graphql/blob/v1.3.5/src/Utils/Preview.php#L22

Stack trace:
```
NOTICE: PHP message: PHP Fatal error: Uncaught TypeError: Argument 3 passed to WPGraphQL\Utils\Preview::filter_post_meta_for_previews() must be of the type string, null given, called in /var/www/wordpress/bedrock/web/wp/wp-includes/class-wp-hook.php on line 294 and defined in /var/www/wordpress/bedrock/web/app/mu-plugins/wp-graphql/src/Utils/Preview.php:22

#0 /var/www/wordpress/bedrock/web/wp/wp-includes/class-wp-hook.php(294): WPGraphQL\Utils\Preview::filter_post_meta_for_previews()

#1 /var/www/wordpress/bedrock/web/wp/wp-includes/plugin.php(212): WP_Hook->apply_filters()

#2 /var/www/wordpress/bedrock/web/wp/wp-includes/meta.php(564): apply_filters()

#3 /var/www/wordpress/bedrock/web/wp/wp-includes/meta.php(506): get_metadata_raw()

#4 /var/www/wordpress/bedrock/web/wp/wp-includes/post.php(2226): get_metadata()

#5 /var/www/wordpress/bedrock/web/app/mu-plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php(1786): get_post_meta()

#6 /var/www/wordpress/bedrock/web/app/mu-plugins/cloudinary-image-manage in /var/www/wordpress/bedrock/web/app/mu-plugins/wp-graphql/src/Utils/Preview.php on line 22

```

**Comment by Vdeub-cloudinary** [comment]
Hi @KevinBerkhof 
Thanks for sharing all those details.
I am checking internally this issue and I will get back to you when I have insights to share.
Best,
Loic

**Comment by pereirinha** [comment]
Hi @KevinBerkhof 

This week we released a new version of the Cloudinary plugin. In it, we addressed this specific issue.
Can you please confirm that this is now resolved?

Thank you.
