### ISSUE TITLE
Delivery type seems missing in URL

### ISSUE THREAD

**Issue by KevinBerkhof** [cloudinary/cloudinary_wordpress#414]
Hi,

It seems that the delivery type is missing for the uploaded files.
When I check the url it is like `https://res.cloudinary.com/<cloud>/images/f_auto,q_auto/v1618217227/filename-6400847/filename.jpg` and it's just working. 

Although I would have expected something like 
`https://res.cloudinary.com/<cloud>/images/upload/f_auto,q_auto/v1618217227/filename-6400847/filename.jpg`
(with the additional delivery type like `upload`)

Is there a setting or something that I'm missing over here why the delivery type is not set?

**Comment by Vdeub-cloudinary** [comment]
Hi @KevinBerkhof, 
When using the plugin, we are actually using the SEO type URLs as defined [here](https://cloudinary.com/documentation/advanced_url_delivery_options#seo_friendly_media_asset_urls). Note that as for now we do not support other types other than `upload` but we are working on it.
