### ISSUE TITLE
Some missing thumbnails in Media Library

### ISSUE THREAD

**Issue by dbrabyn** [cloudinary/cloudinary_wordpress#470]
A few images are not syncing with Cloudinary.

As a result no thumbnail is displaying in grid mode (in list mode I see the local WP thumbnail) and when attempting to embed in a post I can only embed the local version.

In the Media library I see them marked as "_Uploading to new cloud name_". The images that have synced are marked as "_Updating breakpoints_".

```
            "_cloudinary_v2": {
                "_plugin_version": "2.7.4",

                "_process_log": []
            },

        "version": "2.7.4",
        "status": {
            "status": "ok"
        },

        "sync_media": {
            "auto_sync": "on",
            "cloudinary_folder": ".",
            "offload": "dual_full"
        },

```

Possibly relevant plugins in use:
"Name": "**Photo Engine (WP/LR Sync)**",
"PluginURI": "https://meowapps.com",
"Version": "6.0.8",

"Name": "**Smush**",
"PluginURI": "http://wordpress.org/plugins/wp-smushit/",
"Version": "3.8.7",

**Comment by Vdeub-cloudinary** [comment]
Hi @dbrabyn,

Does it happen to newly uploaded assets or not?

In order to be able to further investigate the issue you're experiencing, may I kindly ask you to provide me with the following details:

- WordPress version.
- Cloudinary Plugin's version.
- The theme that you use and its version.
- A full list of all other plugins that you have installed on your environment.
- Page builders that you actively use.
- A screenshot of your Media Library in list mode.
- A screenshot of your Site Health under the Tools Section.
- Hosting providers & Plan (AWS, WP-Engine, etc..)
- Multisite environment (subdomain/subdirectory)
- CLI Access
- A database export of the `wp_posts` and `wp_postmeta` table

Note that since version 2.7.0, you can use the new [system report](https://cloudinary.com/documentation/wordpress_integration#system_report)feature in order to generate all the information above except the screenshots.

Thanks!

**Comment by dbrabyn** [comment]
It seems it doesn't happen to newly uploaded assets. Images uploaded yesterday are ok.

**WordPress version:** 5.7.2
**Cloudinary Plugin's version:** 2.7.4
**Theme in use:** custom theme
**Page builders:** none
**Multisite:** no
**Hosting provider:** FlyWheeel
**A screenshot of your Media Library in list mode:** attached
**A screenshot of your Site Health under the Tools Section:** attached (NB: background updates are disabled by hosting provider)
**All other plugins installed:**
Admin Columns	Version 4.3.2 by AdminColumns.com
Admin Post Navigation	Version 2.1 by Scott Reilly
Advanced Custom Fields: Restrict Color Picker Options	Version 1.3.1 by Vital
Advanced Custom Fields PRO	Version 5.9.7 by Delicious Brains
Akismet Anti-Spam	Version 4.1.9 by Automattic
Asset CleanUp: Page Speed Booster	Version 1.3.7.9 by Gabe Livan
Beehive Analytics	Version 3.3.10 by WPMU DEV
Classic Editor	Version 1.6 by WordPress Contributors
Clean WP Admin Menu	Version 1.0.1 by Bora Yalcin
Cloudinary	Version 2.7.4 by Cloudinary Ltd., XWP
Cookie Notice & Compliance for GDPR / CCPA	Version 2.0.4 by Hu-manity.co
Custom Post Type UI	Version 1.9.2 by WebDevStudios
Fonts Plugin | Google Fonts Typography	Version 2.5.9 by Fonts Plugin
Formidable Forms	Version 4.11.03 by Strategy11
Glance That	Version 4.9 by Typewheel
Intuitive Custom Post Order	Version 3.1.3 by hijiri
Lazy Load for Videos	Version 2.16.1 by Kevin Weber
ManageWP - Worker	Version 4.9.8 by GoDaddy
Photo Engine (WP/LR Sync)	Version 6.0.8 by Jordy Meow
reCaptcha by BestWebSoft	Version 1.62 by BestWebSoft
Redirection	Version 5.1.1 by John Godley
Regenerate Thumbnails	Version 3.1.5 by Alex Mills (Viper007Bond)
Smush	Version 3.8.7 by WPMU DEV
WP-PageNavi	Version 2.94.0 by Lester 'GaMerZ' Chan
wpDiscuz	Version 7.2.2 by gVectors Team
Yoast SEO	Version 16.6.1 by Team Yeast

Client says it is a new-ish issue that might have appeared with the June 23rd update. He says it looks like it is happening with images already on the site, which he adds to another collection (folder) in the Photo Engine plug-in (there’s still only one instance of the asset in the Media Library, but Photo Engine shows the image in multiple “folders” in its organizer -- really just filters in the Media Library).

**Comment by Vdeub-cloudinary** [comment]
@dbrabyn - thanks for sharing the details, however, it doesn't look like the screenshots are being added. Could you please open a ticket to support@cloudinary.com specifying this Github issue? 

On another note, it would be great to have the database export of the `wp_posts` and `wp_postmeta` table at least we can compare the `guid` value of images that are synced and images that are not - I presume there might be a difference here that could explain why newly uploaded images work.

Thanks!

**Comment by dbrabyn** [comment]
Sent. Thanks.
