### ISSUE TITLE
Existing media keeps status "copying to folder"

### ISSUE THREAD

**Issue by jvwijhe** [cloudinary/cloudinary_wordpress#543]
Existing media won't upload to Cloudinary after changing the "Cloudinary folder path". New media is uploading fine and showing up in Cloudinary. 

After changing the "Cloudinary folder path" value in the media settings the public_id value of an existing asset json meta data keeps returning an old value.  In the media library all existing assets have the status "Copying to folder ..." 

In the Cloudinary plugin media settings the bulk sync options keeps the status "syncing" for several days.

**Comment by wissam-khalili** [comment]
Hi there,
Could you please create a ticket to _support@cloudinary.com_ with the system report attached as explained [here](https://cloudinary.com/documentation/wordpress_integration#system_report)? Could you also please, before generating the report, make sure that you include images in your report as explained [here](https://cloudinary.com/documentation/wordpress_integration#adding_media_or_posts_pages_to_the_report)?
In case it will be necessary, will you be willing to provide us with temporary access to a sandbox environment of your site where we can take a look and debug if needed?

Thanks,
Wissam
