### ISSUE TITLE
Cloudinary URL no longer returned.

### ISSUE THREAD

**Issue by matt-antone** [cloudinary/cloudinary_wordpress#625]
Upgraded from 2 to 3 and now I only get the local URL and not the cloudinary URL.

$logo = wp_get_attachment_image_src( $custom_logo_id, 'full');
$logo2 = wp_get_attachment_image( $custom_logo_id, 'full');
error_log(print_r(array($logo,$logo2),true));

[07-Dec-2021 19:31:37 UTC] Array
(
    [0] => Array
        (
            [0] => http://montage2.local/wp-content/uploads/2021/11/main_logo.png
            [1] => 264
            [2] => 315
            [3] => 
        )

    [1] => <img width="264" height="315" src="http://montage2.local/wp-content/uploads/2021/11/main_logo.png" class="attachment-full size-full" alt="" loading="lazy" srcset="http://montage2.local/wp-content/uploads/2021/11/main_logo.png 264w, http://montage2.local/wp-content/uploads/2021/11/main_logo-251x300.png 251w" sizes="(max-width: 264px) 100vw, 264px" />
)

SYSTEM REPORT

{
    "system_status": {
        "home": "http://montage2.local",
        "wordpress": "5.8.2",
        "php": "7.3.5",
        "php_extensions": [
            "Core",
            "date",
            "libxml",
            "openssl",
            "pcre",
            "zlib",
            "bcmath",
            "bz2",
            "calendar",
            "ctype",
            "curl",
            "dom",
            "hash",
            "fileinfo",
            "filter",
            "ftp",
            "gd",
            "gettext",
            "SPL",
            "iconv",
            "json",
            "mbstring",
            "session",
            "standard",
            "pcntl",
            "mysqlnd",
            "PDO",
            "pdo_mysql",
            "Phar",
            "posix",
            "Reflection",
            "mysqli",
            "shmop",
            "SimpleXML",
            "soap",
            "sockets",
            "exif",
            "tokenizer",
            "xml",
            "xmlreader",
            "xmlrpc",
            "xmlwriter",
            "xsl",
            "zip",
            "cgi-fcgi",
            "Zend OPcache",
            "xdebug"
        ]
    },
    "theme_status": {
        "name": "TailPress Headless",
        "version": "1.0.0",
        "author": "Jeffrey van Rossum",
        "author_url": "https://vanrossum.dev",
        "child_theme": false
    },
    "plugins_report": {
        "must_use": [
            "/Users/antone/Dropbox (Personal)/Local Sites/montage2/app/public/wp-content/mu-plugins/sso.php"
        ],
        "plugins": [
            {
                "Name": "Advanced Custom Fields: Extended",
                "PluginURI": "",
                "Version": "0.8.8.6",
                "Description": "All-in-one enhancement suite that improves WordPress &amp; Advanced Custom Fields. <cite>By <a href=\"https://www.acf-extended.com\">ACF Extended</a>.</cite>",
                "Author": "<a href=\"https://www.acf-extended.com\">ACF Extended</a>",
                "AuthorURI": "https://www.acf-extended.com",
                "TextDomain": "acfe",
                "DomainPath": "/lang",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "Advanced Custom Fields: Extended",
                "AuthorName": "ACF Extended"
            },
            {
                "Name": "Add WPGraphQL SEO",
                "PluginURI": "https://github.com/ashhitch/wp-graphql-yoast-seo",
                "Version": "4.16.0",
                "Description": "A WPGraphQL Extension that adds support for Yoast SEO <cite>By <a href=\"https://www.ashleyhitchcock.com\">Ash Hitchcock</a>.</cite>",
                "Author": "<a href=\"https://www.ashleyhitchcock.com\">Ash Hitchcock</a>",
                "AuthorURI": "https://www.ashleyhitchcock.com",
                "TextDomain": "wp-graphql-yoast-seo",
                "DomainPath": "/languages",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://github.com/ashhitch/wp-graphql-yoast-seo\">Add WPGraphQL SEO</a>",
                "AuthorName": "Ash Hitchcock"
            },
            {
                "Name": "Advanced Custom Fields PRO",
                "PluginURI": "https://www.advancedcustomfields.com",
                "Version": "5.11.4",
                "Description": "Customize WordPress with powerful, professional and intuitive fields. <cite>By <a href=\"https://www.advancedcustomfields.com\">Delicious Brains</a>.</cite>",
                "Author": "<a href=\"https://www.advancedcustomfields.com\">Delicious Brains</a>",
                "AuthorURI": "https://www.advancedcustomfields.com",
                "TextDomain": "acf",
                "DomainPath": "/lang",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://www.advancedcustomfields.com\">Advanced Custom Fields PRO</a>",
                "AuthorName": "Delicious Brains"
            },
            {
                "Name": "All-in-One WP Migration Unlimited Extension",
                "PluginURI": "https://servmask.com/",
                "Version": "2.42",
                "Description": "Extension for All-in-One WP Migration that enables unlimited size exports and imports <cite>By <a href=\"https://servmask.com/\">ServMask</a>.</cite>",
                "Author": "<a href=\"https://servmask.com/\">ServMask</a>",
                "AuthorURI": "https://servmask.com/",
                "TextDomain": "all-in-one-wp-migration-unlimited-extension",
                "DomainPath": "/languages",
                "Network": true,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://servmask.com/\">All-in-One WP Migration Unlimited Extension</a>",
                "AuthorName": "ServMask"
            },
            {
                "Name": "All-in-One WP Migration",
                "PluginURI": "https://servmask.com/",
                "Version": "7.50",
                "Description": "Migration tool for all your blog data. Import or Export your blog content with a single click. <cite>By <a href=\"https://servmask.com/\">ServMask</a>.</cite>",
                "Author": "<a href=\"https://servmask.com/\">ServMask</a>",
                "AuthorURI": "https://servmask.com/",
                "TextDomain": "all-in-one-wp-migration",
                "DomainPath": "/languages",
                "Network": true,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://servmask.com/\">All-in-One WP Migration</a>",
                "AuthorName": "ServMask"
            },
            {
                "Name": "Bluehost",
                "PluginURI": "",
                "Version": "2.8.5",
                "Description": "This plugin integrates your WordPress site with the Bluehost control panel, including performance, security, and update features. <cite>By <a href=\"https://www.bluehost.com/\">Bluehost</a>.</cite>",
                "Author": "<a href=\"https://www.bluehost.com/\">Bluehost</a>",
                "AuthorURI": "https://www.bluehost.com/",
                "TextDomain": "bluehost-wordpress-plugin",
                "DomainPath": "/languages",
                "Network": false,
                "RequiresWP": "4.7",
                "RequiresPHP": "5.6",
                "UpdateURI": "",
                "Title": "Bluehost",
                "AuthorName": "Bluehost"
            },
            {
                "Name": "Cloudinary",
                "PluginURI": "https://cloudinary.com/documentation/wordpress_integration",
                "Version": "3.0.0",
                "Description": "With the Cloudinary plugin, you can upload and manage your media assets in the cloud, then deliver them to your users through a fast content delivery network, improving your website\u2019s loading speed and overall user experience. Apply multiple transformations and take advantage of a full digital asset management solution without leaving WordPress. <cite>By <a href=\"https://cloudinary.com/\">Cloudinary Ltd., XWP</a>.</cite>",
                "Author": "<a href=\"https://cloudinary.com/\">Cloudinary Ltd., XWP</a>",
                "AuthorURI": "https://cloudinary.com/",
                "TextDomain": "cloudinary",
                "DomainPath": "/languages",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://cloudinary.com/documentation/wordpress_integration\">Cloudinary</a>",
                "AuthorName": "Cloudinary Ltd., XWP"
            },
            {
                "Name": "Custom Post Type UI",
                "PluginURI": "https://github.com/WebDevStudios/custom-post-type-ui/",
                "Version": "1.10.0",
                "Description": "Admin panel for creating custom post types and custom taxonomies in WordPress <cite>By <a href=\"https://webdevstudios.com/\">WebDevStudios</a>.</cite>",
                "Author": "<a href=\"https://webdevstudios.com/\">WebDevStudios</a>",
                "AuthorURI": "https://webdevstudios.com/",
                "TextDomain": "custom-post-type-ui",
                "DomainPath": "/languages",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://github.com/WebDevStudios/custom-post-type-ui/\">Custom Post Type UI</a>",
                "AuthorName": "WebDevStudios"
            },
            {
                "Name": "Disable Comments",
                "PluginURI": "https://wordpress.org/plugins/disable-comments/",
                "Version": "2.2.4",
                "Description": "Allows administrators to globally disable comments on their site. Comments can be disabled according to post type. You could bulk delete comments using Tools. <cite>By <a href=\"https://wpdeveloper.net\">WPDeveloper</a>.</cite>",
                "Author": "<a href=\"https://wpdeveloper.net\">WPDeveloper</a>",
                "AuthorURI": "https://wpdeveloper.net",
                "TextDomain": "disable-comments",
                "DomainPath": "/languages/",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://wordpress.org/plugins/disable-comments/\">Disable Comments</a>",
                "AuthorName": "WPDeveloper"
            },
            {
                "Name": "Enable Media Replace",
                "PluginURI": "https://wordpress.org/plugins/enable-media-replace/",
                "Version": "3.6.3",
                "Description": "Enable replacing media files by uploading a new file in the &#8220;Edit Media&#8221; section of the WordPress Media Library. <cite>By <a href=\"https://shortpixel.com\">ShortPixel</a>.</cite>",
                "Author": "<a href=\"https://shortpixel.com\">ShortPixel</a>",
                "AuthorURI": "https://shortpixel.com",
                "TextDomain": "enable-media-replace",
                "DomainPath": "/languages",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://wordpress.org/plugins/enable-media-replace/\">Enable Media Replace</a>",
                "AuthorName": "ShortPixel"
            },
            {
                "Name": "Post Type Switcher",
                "PluginURI": "https://wordpress.org/plugins/post-type-switcher",
                "Version": "3.2.1",
                "Description": "A simple way to change a post&#8217;s type in WordPress <cite>By <a href=\"https://jjj.software\">Triple J Software, Inc.</a>.</cite>",
                "Author": "<a href=\"https://jjj.software\">Triple J Software, Inc.</a>",
                "AuthorURI": "https://jjj.software",
                "TextDomain": "post-type-switcher",
                "DomainPath": "/assets/lang/",
                "Network": false,
                "RequiresWP": "5.0",
                "RequiresPHP": "7.0",
                "UpdateURI": "",
                "Title": "<a href=\"https://wordpress.org/plugins/post-type-switcher\">Post Type Switcher</a>",
                "AuthorName": "Triple J Software, Inc."
            },
            {
                "Name": "SVG Support",
                "PluginURI": "http://wordpress.org/plugins/svg-support/",
                "Version": "2.3.19",
                "Description": "Upload SVG files to the Media Library and render SVG files inline for direct styling/animation of an SVG&#8217;s internal elements using CSS/JS. <cite>By <a href=\"https://benbodhi.com\">Benbodhi</a>.</cite>",
                "Author": "<a href=\"https://benbodhi.com\">Benbodhi</a>",
                "AuthorURI": "https://benbodhi.com",
                "TextDomain": "svg-support",
                "DomainPath": "/languages",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"http://wordpress.org/plugins/svg-support/\">SVG Support</a>",
                "AuthorName": "Benbodhi"
            },
            {
                "Name": "UpdraftPlus - Backup/Restore",
                "PluginURI": "https://updraftplus.com",
                "Version": "1.16.66",
                "Description": "Backup and restore: take backups locally, or backup to Amazon S3, Dropbox, Google Drive, Rackspace, (S)FTP, WebDAV &amp; email, on automatic schedules. <cite>By <a href=\"https://updraftplus.com\">UpdraftPlus.Com, DavidAnderson</a>.</cite>",
                "Author": "<a href=\"https://updraftplus.com\">UpdraftPlus.Com, DavidAnderson</a>",
                "AuthorURI": "https://updraftplus.com",
                "TextDomain": "updraftplus",
                "DomainPath": "/languages",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "https://wordpress.org/plugins/updraftplus/",
                "Title": "<a href=\"https://updraftplus.com\">UpdraftPlus - Backup/Restore</a>",
                "AuthorName": "UpdraftPlus.Com, DavidAnderson"
            },
            {
                "Name": "Vercel Deploy Hooks",
                "PluginURI": "https://github.com/aderaaij/wp-vercel-deploy-hooks",
                "Version": "1.3.0",
                "Description": "WordPress plugin for building your Vercel static site on command, post publish/update or scheduled <cite>By <a href=\"https://arden.nl\">Arden de Raaij</a>.</cite>",
                "Author": "<a href=\"https://arden.nl\">Arden de Raaij</a>",
                "AuthorURI": "https://arden.nl",
                "TextDomain": "vercel-deploy-hooks",
                "DomainPath": "",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://github.com/aderaaij/wp-vercel-deploy-hooks\">Vercel Deploy Hooks</a>",
                "AuthorName": "Arden de Raaij"
            },
            {
                "Name": "Wordfence Security",
                "PluginURI": "http://www.wordfence.com/",
                "Version": "7.5.7",
                "Description": "Wordfence Security &#8211; Anti-virus, Firewall and Malware Scan <cite>By <a href=\"http://www.wordfence.com/\">Wordfence</a>.</cite>",
                "Author": "<a href=\"http://www.wordfence.com/\">Wordfence</a>",
                "AuthorURI": "http://www.wordfence.com/",
                "TextDomain": "wordfence",
                "DomainPath": "/languages",
                "Network": true,
                "RequiresWP": "3.9",
                "RequiresPHP": "5.3",
                "UpdateURI": "",
                "Title": "<a href=\"http://www.wordfence.com/\">Wordfence Security</a>",
                "AuthorName": "Wordfence"
            },
            {
                "Name": "Yoast SEO",
                "PluginURI": "https://yoa.st/1uj",
                "Version": "17.7.1",
                "Description": "The first true all-in-one SEO solution for WordPress, including on-page content analysis, XML sitemaps and much more. <cite>By <a href=\"https://yoa.st/1uk\">Team Yoast</a>.</cite>",
                "Author": "<a href=\"https://yoa.st/1uk\">Team Yoast</a>",
                "AuthorURI": "https://yoa.st/1uk",
                "TextDomain": "wordpress-seo",
                "DomainPath": "/languages/",
                "Network": false,
                "RequiresWP": "5.6",
                "RequiresPHP": "5.6.20",
                "UpdateURI": "",
                "Title": "<a href=\"https://yoa.st/1uj\">Yoast SEO</a>",
                "AuthorName": "Team Yoast"
            },
            {
                "Name": "WPGraphQL for Advanced Custom Fields",
                "PluginURI": "https://wpgraphql.com/acf",
                "Version": "0.5.3",
                "Description": "Adds Advanced Custom Fields to the WPGraphQL Schema <cite>By <a href=\"https://www.wpgraphql.com\">WPGraphQL, Jason Bahl</a>.</cite>",
                "Author": "<a href=\"https://www.wpgraphql.com\">WPGraphQL, Jason Bahl</a>",
                "AuthorURI": "https://www.wpgraphql.com",
                "TextDomain": "wp-graphql-acf",
                "DomainPath": "/languages",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "7.0",
                "UpdateURI": "",
                "Title": "<a href=\"https://wpgraphql.com/acf\">WPGraphQL for Advanced Custom Fields</a>",
                "AuthorName": "WPGraphQL, Jason Bahl"
            },
            {
                "Name": "WPGraphQL Cache",
                "PluginURI": "https://github.com/valu-digital/wp-graphql-cache",
                "Version": "0.0.7",
                "Description": "Add caching for WPGraphQL <cite>By Esa-Matti Suuronen, Valu Digital Oy.</cite>",
                "Author": "Esa-Matti Suuronen, Valu Digital Oy",
                "AuthorURI": "",
                "TextDomain": "wp-graphql-cache",
                "DomainPath": "",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://github.com/valu-digital/wp-graphql-cache\">WPGraphQL Cache</a>",
                "AuthorName": "Esa-Matti Suuronen, Valu Digital Oy"
            },
            {
                "Name": "WP GraphQL Gutenberg",
                "PluginURI": "https://github.com/pristas-peter/wp-graphql-gutenberg",
                "Version": "0.3.11",
                "Description": "Enable blocks in WP GraphQL. <cite>By pristas-peter.</cite>",
                "Author": "pristas-peter",
                "AuthorURI": "",
                "TextDomain": "wp-graphql-gutenberg-0.3.11",
                "DomainPath": "",
                "Network": false,
                "RequiresWP": "5.4",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://github.com/pristas-peter/wp-graphql-gutenberg\">WP GraphQL Gutenberg</a>",
                "AuthorName": "pristas-peter"
            },
            {
                "Name": "WP GraphQL Gutenberg ACF",
                "PluginURI": "https://github.com/pristas-peter/wp-graphql-gutenberg-acf",
                "Version": "0.3.0",
                "Description": "Enable acf blocks in WP GraphQL. <cite>By pristas-peter.</cite>",
                "Author": "pristas-peter",
                "AuthorURI": "",
                "TextDomain": "wp-graphql-gutenberg-acf-0.3.0",
                "DomainPath": "",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "<a href=\"https://github.com/pristas-peter/wp-graphql-gutenberg-acf\">WP GraphQL Gutenberg ACF</a>",
                "AuthorName": "pristas-peter"
            },
            {
                "Name": "WP GraphQL",
                "PluginURI": "https://github.com/wp-graphql/wp-graphql",
                "Version": "1.6.7",
                "Description": "GraphQL API for WordPress <cite>By <a href=\"http://www.wpgraphql.com\">WPGraphQL</a>.</cite>",
                "Author": "<a href=\"http://www.wpgraphql.com\">WPGraphQL</a>",
                "AuthorURI": "http://www.wpgraphql.com",
                "TextDomain": "wp-graphql",
                "DomainPath": "/languages/",
                "Network": false,
                "RequiresWP": "5.0",
                "RequiresPHP": "7.1",
                "UpdateURI": "",
                "Title": "<a href=\"https://github.com/wp-graphql/wp-graphql\">WP GraphQL</a>",
                "AuthorName": "WPGraphQL"
            }
        ]
    },
    "media_report": {
        "786": {
            "width": 7358,
            "height": 4910,
            "file": "2016/09/VIVIO_027.jpg",
            "sizes": {
                "thumbnail": {
                    "file": "VIVIO_027-150x150.jpg",
                    "width": 150,
                    "height": 150,
                    "mime-type": "image/jpeg"
                },
                "medium": {
                    "file": "VIVIO_027-300x200.jpg",
                    "width": 300,
                    "height": 200,
                    "mime-type": "image/jpeg"
                },
                "medium_large": {
                    "file": "VIVIO_027-768x512.jpg",
                    "width": 768,
                    "height": 512,
                    "mime-type": "image/jpeg"
                },
                "large": {
                    "file": "VIVIO_027-1024x683.jpg",
                    "width": 1024,
                    "height": 683,
                    "mime-type": "image/jpeg"
                },
                "Featured Image": {
                    "file": "VIVIO_027-1000x500.jpg",
                    "width": 1000,
                    "height": 500,
                    "mime-type": "image/jpeg"
                },
                "Slide Image": {
                    "file": "VIVIO_027-300x300.jpg",
                    "width": 300,
                    "height": 300,
                    "mime-type": "image/jpeg"
                },
                "Preview Image": {
                    "file": "VIVIO_027-1000x1000.jpg",
                    "width": 1000,
                    "height": 1000,
                    "mime-type": "image/jpeg"
                }
            },
            "image_meta": {
                "aperture": "9",
                "credit": "",
                "camera": "NIKON D800E",
                "caption": "",
                "created_timestamp": "1444127527",
                "copyright": "Paul D Mullins",
                "focal_length": "16",
                "iso": "50",
                "shutter_speed": "0",
                "title": "",
                "orientation": "1",
                "keywords": []
            },
            "attachment": {
                "ID": 786,
                "post_author": "2",
                "post_date": "2016-09-16 18:22:13",
                "post_date_gmt": "2016-09-16 18:22:13",
                "post_content": "",
                "post_title": "Avivo Bathroom",
                "post_excerpt": "",
                "post_status": "inherit",
                "comment_status": "open",
                "ping_status": "closed",
                "post_password": "",
                "post_name": "vivio_027-2",
                "to_ping": "",
                "pinged": "",
                "post_modified": "2016-09-16 18:51:44",
                "post_modified_gmt": "2016-09-16 18:51:44",
                "post_content_filtered": "",
                "post_parent": 0,
                "guid": "http://montage2.local/wp-content/uploads/2016/09/VIVIO_027.jpg",
                "menu_order": 0,
                "post_type": "attachment",
                "post_mime_type": "image/jpeg",
                "comment_count": "0",
                "filter": "raw"
            },
            "all_meta": {
                "_wp_attached_file": [
                    "2016/09/VIVIO_027.jpg"
                ],
                "_wp_attachment_metadata": [
                    {
                        "width": 7358,
                        "height": 4910,
                        "file": "2016/09/VIVIO_027.jpg",
                        "sizes": {
                            "thumbnail": {
                                "file": "VIVIO_027-150x150.jpg",
                                "width": 150,
                                "height": 150,
                                "mime-type": "image/jpeg"
                            },
                            "medium": {
                                "file": "VIVIO_027-300x200.jpg",
                                "width": 300,
                                "height": 200,
                                "mime-type": "image/jpeg"
                            },
                            "medium_large": {
                                "file": "VIVIO_027-768x512.jpg",
                                "width": 768,
                                "height": 512,
                                "mime-type": "image/jpeg"
                            },
                            "large": {
                                "file": "VIVIO_027-1024x683.jpg",
                                "width": 1024,
                                "height": 683,
                                "mime-type": "image/jpeg"
                            },
                            "Featured Image": {
                                "file": "VIVIO_027-1000x500.jpg",
                                "width": 1000,
                                "height": 500,
                                "mime-type": "image/jpeg"
                            },
                            "Slide Image": {
                                "file": "VIVIO_027-300x300.jpg",
                                "width": 300,
                                "height": 300,
                                "mime-type": "image/jpeg"
                            },
                            "Preview Image": {
                                "file": "VIVIO_027-1000x1000.jpg",
                                "width": 1000,
                                "height": 1000,
                                "mime-type": "image/jpeg"
                            }
                        },
                        "image_meta": {
                            "aperture": "9",
                            "credit": "",
                            "camera": "NIKON D800E",
                            "caption": "",
                            "created_timestamp": "1444127527",
                            "copyright": "Paul D Mullins",
                            "focal_length": "16",
                            "iso": "50",
                            "shutter_speed": "0",
                            "title": "",
                            "orientation": "1",
                            "keywords": []
                        }
                    }
                ],
                "_cloudinary": [
                    {
                        "_file_size": 22102111
                    }
                ],
                "_cld_error": [
                    "File size exceeds the maximum of 10 MB. This media asset will be served from WordPress."
                ],
                "_cloudinary_process_log": []
            }
        }
    },
    "post_report": {
        "788": null,
        "511": null
    },
    "config_report": {
        "gallery": {
            "transition": "fade",
            "aspectRatio": "3:4",
            "navigation": "always",
            "zoom": true,
            "carouselLocation": "top",
            "carouselOffset": 5,
            "carouselStyle": "thumbnails",
            "displayProps": {
                "mode": "classic",
                "columns": 1
            },
            "indicatorProps": {
                "shape": "round"
            },
            "themeProps": {
                "primary": "#cf2e2e",
                "onPrimary": "#000000",
                "active": "#777777"
            },
            "zoomProps": {
                "type": "popup",
                "viewerPosition": "bottom",
                "trigger": "click"
            },
            "thumbnailProps": {
                "width": 64,
                "height": 64,
                "navigationShape": "radius",
                "selectedStyle": "gradient",
                "selectedBorderPosition": "all",
                "selectedBorderWidth": 4,
                "mediaSymbolShape": "round"
            },
            "cloudName": "montage",
            "container": "",
            "queryParam": "AA"
        }
    }
}

**Comment by Vdeub-cloudinary** [comment]
Hi @matt-antone,

Do you mind sharing a system report with the `main-logo` image added to it? Looking at your report, I can only see 1 image that won't be served through Cloudinary as it exceeds the limit. 

Thanks!

**Comment by jiaoqiqi** [comment]
Hi @Vdeub-cloudinary, I have the same issue when use `wp_get_attachment_image_src` to get the image url.
Like in media library page, the image url is from cloudinary, but from the method, I got image url is from the local one. What's the solution for this?
