### ISSUE TITLE
Improper File Dimensions in SrcSet

### ISSUE THREAD

**Issue by awcodes** [cloudinary/cloudinary_wordpress#659]
I've noticed an issue with invalid width and height transforms being generated in srcsets for images whose file name ends in anything after the last hyphen that contains an 'x' character. This is also leading to large numbers of 40x errors in our reports in combination with the lazy loading plugin.

example:
'timeline-iconic-cars-film-history-4_max_thumb.png' generates a w_4,h_0 transformation due to how it is parsed in the code

I've tracked the issue down to the get_size_from_url() function in the Media Class (php/class-media.php) on line 793.

The following conditional would fix the issue:
It uses an additional RegEx check to validate if the $end_part is a possible dimension or not.

```
if ((false !== $end_part || false !== strpos($end_part, 'x')) && preg_match('/^[0-9]*x[0-9]*$/', $end_part)) {
  $size_parts = explode('x', $end_part);
  $size_int   = array_map('intval', $size_parts);
  $size       = array_filter($size_int, 'is_int');

  if (!empty($size) && 2 === count($size)) {
	$return = $size;
  }
}
```

If I can find some more time I'll submit a PR, but thought you should at least be aware of the issue.

Thank you for the awesome plugin and service.

**Comment by DavidCramer** [comment]
Hi @awcodes - Thanks for this. We have identified the issue as well, and have already made a fix for the next release.

Really appreciate you taking the time to look into it.

**Comment by awcodes** [comment]
Thank you so David. Glad to hear it.
