### ISSUE TITLE
Can't add an image from Cloudinary to the Image Block

### ISSUE THREAD

**Issue by amooreTO** [cloudinary/cloudinary_wordpress#669]
I am using WordPress 5.8.3 with the latest version of the Cloudinary plugin.  I also have the Cloudinary DAM extension installed.

It does not look like you can insert an image from Cloundary onto the image block.

**Steps to reproduce:**

1. Add the Image block to a page
2. Click on "Media Library"
3. Click on the "Cloudinary" tab
4. Click on the image you want to use
5. There is no Insert button 

The expectation is that I can insert an image from Cloundary to be used on default WordPress blocks.

**Comment by Vdeub-cloudinary** [comment]
Hi @amooreTO, you should have an `import` button as you can see on the screenshot attached
<img width="1748" alt="Screenshot 2022-01-20 at 12 03 38" src="https://user-images.githubusercontent.com/66945106/150335489-f8b9b290-be1f-4865-8929-1956438ca17b.png">

The DAM extension is different and lets you import assets when you are not on a page/post using the following flow:

1. Clicking on DAM extension opens the Cloudinary Media Library.
2. You can select up to 20 assets and click on `import`. 
3.  Those assets will show directly into your WordPress Media Library.

**Comment by amooreTO** [comment]
@Vdeub-cloudinary got it thanks. So the images from the DAM must be in the WordPress Media Library, and then you insert the image onto a page/block from WordPress versus the DAM.

Thanks for clarifying.

**Comment by Vdeub-cloudinary** [comment]
@amooreTO, you actually have 2 options - the one you did where you should see the `import` button and the new DAM extension that doesn't require to be on a post/page.
