### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by FreddyFY** [cloudinary/cloudinary_wordpress#677]
Hi there,

when using this Plugin on a Server with PHP 8.1.1, it throws this error:

```
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /var/www/vhosts/.../httpdocs/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-admin.php on line 398
```

**Comment by wissam-khalili** [comment]
Hi @FreddyFY ,

Thank you for reaching out.
We will review the issue and we will keep you posted.

Thanks,
Wissam

**Comment by wissam-khalili** [comment]
According to the [PHP documentation](https://www.php.net/manual/en/filter.filters.sanitize.php), we should be using [htmlspecialchars()](https://www.php.net/manual/en/function.htmlspecialchars.php) instead, as of PHP 8.1.

As for the rtrim() warning, this isn’t our code. In the single instance in which we use this function, there’s no way that the content passed is null.

**Comment by wissam-khalili** [comment]
Hi @FreddyFY,

Please note that the latest version 3.0.3 was released.
Could you please upgrade and check if it resolves this issue?

Regards,
Wissam
