### ISSUE TITLE
Cloudinary URL no returned for background url in css

### ISSUE THREAD

**Issue by arunsureshkumar** [cloudinary/cloudinary_wordpress#693]
background: url("") width and height to automatically determine what to keep in a banner crop

**Comment by Vdeub-cloudinary** [comment]
@arunsureshkumar, this is strange as it should work properly. Would you mind creating a ticket to support@cloudinary.com with:

- A system report (Need Help? under the Cloudinary plugin --> System report icon) with 
the asset not being displayed added to it (2nd video [here](https://support.cloudinary.com/hc/en-us/articles/360022260599-How-to-generate-a-system-report-on-the-WordPress-plugin-))
<img width="1787" alt="Screenshot 2022-01-28 at 11 34 04" src="https://user-images.githubusercontent.com/66945106/155286548-41d56c1a-873c-482c-bc3d-99a6583b2e81.png">
- An example URL of your website with the issue.
- The code you are using to build your element. 
- A screenshot of your Media Library in list mode showing the asset.
