### ISSUE TITLE
Cloudinary URLs for WPGraphQL Yoast SEO Addon

### ISSUE THREAD

**Issue by ttstauss** [cloudinary/cloudinary_wordpress#711]
I know there are other issues already created for Cloudinary URLs populating correctly for WPGraphQL, but I think there's a subtle difference in what I'm facing (not pulling images from the content or raw HTML).

I'm using the `WPGraphQL Yoast SEO Addon` to query SEO data from the Yoast general settings and individual Post/Page Yoast settings.

When I set up a Facebook social image in the Yoast general settings, I get a WordPress-based URL instead of a Cloudinary URL.

In addition to that, when I set the Facebook or Twitter images on a specific Post/Page, I get `null` for the `opengraphImage` result and a WordPress URL for the `twitterImage` result.

**Comment by Vdeub-cloudinary** [comment]
Hi @ttstauss, it is not currently supported but we think the next version `3.0.3` might help here.
In any case, our dev team will have a look and we will let you know when we have any insights to share.

**Comment by Vdeub-cloudinary** [comment]
Hi @ttstauss, we have just released `3.0.3`, could you please upgrade the plugin and see if that fixes your issue?

**Comment by ttstauss** [comment]
Hi @Vdeub-cloudinary, do I need to do anything else besides upgrading the plugin? My initial testing doesn't show any changes (I removed and readded the images in question).
