### ISSUE TITLE
Cloudinary v3.0.4 incompatible with Elementor plugin when saving Chinese text

### ISSUE THREAD

**Issue by chuenlum** [cloudinary/cloudinary_wordpress#762]
## Bug Description

Editing page in Elementor with Cloudinary v3.0.4 installed results in Chinese text not showing well (slash is stripped).

## Expected Behaviour

See below

## Steps to reproduce

1. Deactivate all plugins except Elementor v3.6.6 and Cloudinary v3.0.4
2. Edit any page using Elementor and type in a mixture of English and Chinese characters, for example: "Chinese 中文".
3. Save the page while in Elementor editor view
4. Open the saved page

**Expect**: text shows "Chinese 中文"
**Actual**: text shows "Chinese U4e2du6587". Note that unicode for 中文 is \u4e2d\u6587

Also note that if an Elementor page template was saved, saving any Chinese text results in the whole page becoming blank - all page content is lost.

## Screenshots

See video: https://user-images.githubusercontent.com/12426535/172898656-3f3a40cb-3e4a-4a12-8e45-22fb224d594c.mp4

## Additional context

 - WordPress version:
 - Plugin version: 3.0.4
 - PHP version: 7.4.3

Note that this issue doesn't appear with Cloudinary 3.0.3.

**Comment by Vdeub-cloudinary** [comment]
Hi @chuenlum,
We are aware of an issue with Elementor Pro on `3.0.4`. Would you mind opening a ticket to support@cloudinary.com and share a system report as explained [here](https://support.cloudinary.com/hc/en-us/articles/360022260599-How-to-generate-a-system-report-on-the-WordPress-plugin-)?
Thanks!
