### ISSUE TITLE
PHPCompatibiltyWP missing from PHPCS config file

### ISSUE THREAD

**Issue by GaryJones** [cloudinary/cloudinary_wordpress#791]
## Bug Description

A `testVersion` configuration value in the PHPCS config file was [uncommented](https://github.com/cloudinary/cloudinary_wordpress/commit/d8bc42264d4179d00e44a56669faccf265e3b5db) by @pereirinha, but it still doesn't have any effect until the PHPCompatibility or PHPCompatibilityWP rule is added. The line was previously [commented out](https://github.com/cloudinary/cloudinary_wordpress/commit/19064d2ff8c57c51e9fdde059649e7562c159d87) because it wasn't having any effect then. 

## Expected Behaviour

The [PHPCS config](https://github.com/cloudinary/cloudinary_wordpress/blob/master/phpcs.xml.dist) file should contain something like:

```xml
<!-- Rules: Check PHP version compatibility - see
		https://github.com/PHPCompatibility/PHPCompatibilityWP -->
<rule ref="PHPCompatibilityWP"/>
```

## Steps to reproduce

[PHPCompatibilityWP has been added as a dev dependency](https://github.com/cloudinary/cloudinary_wordpress/commit/2a61cf1df75583e3af2f3ef405580e910cc668e5) (good), but it isn't in the [PHPCS config](https://github.com/cloudinary/cloudinary_wordpress/blob/master/phpcs.xml.dist) where it would be expected to be found along with the other ruleset references.

See https://github.com/Parsely/wp-parsely/blob/d0384362e1815aa557a5447b738d8bac58dbcb80/.phpcs.xml.dist#L30-L35 as an example.

**Comment by GaryJones** [comment]
Separately, I'll also note that you have the `*` constraint for the `PHPCompatibilityWP` package. This will also pull in  `PHPCompatibility` v9, but that doesn't have the sniffs related to PHP 8.

Please follow the steps at https://docs.wpvip.com/how-tos/code-scanning-for-php-upgrade/#Upcoming-releases-of-PHPCompatibility to use `PHPCompatibilityWP` with `PHPCompatibility` `develop` branch which does contain the PHP 8-related sniffs.

**Comment by PixelCook** [comment]
Gary I've submitted your notes to our production team. Thanks so much! I'll update with any updates I have.

**Comment by pereirinha** [comment]
Thanks, @GaryJones, for raising this.

I did open 2 PR. The [first](https://github.com/cloudinary/cloudinary_wordpress/pull/794) will take care of your suggestions in the configuration files. The [second](https://github.com/cloudinary/cloudinary_wordpress/pull/793) takes care of some code improvements.

It'd be great if you could chime in the first PR.

Luckily, I don't think the code had any pitfall, but we'll be let know from now on.

**Comment by pereirinha** [comment]
This was merged and will be part of the next release.
Closing.
