### ISSUE TITLE
Wordpress "Events Manager" plugin - Image size with crop

### ISSUE THREAD

**Issue by ArboLife** [cloudinary/cloudinary_wordpress#8]
The Events Manager Wordpress plugin (https://wordpress.org/plugins/events-manager/) requests images with the shortcode #_EVENTIMAGE{x,y} where x and y represent the image size. It works with Cloudinary if only one value is supplied, when both are given the image is scaled out of proportion with c_scale. 

I created a code for a custom shortcode #_CUSTOMEVENTIMAGE{100,100} that uses c_fill in the Cloudinary URL when both values are supplied, allowing to fill the dimension provided with the image by cropping it.

The project can be found here: https://github.com/ArboLife/Events-Manager-Cloudinary

**Comment by idobarnoam** [comment]
@ArboLife Thanks for the addition! 
I'm sorry for the late response here.
We would look into this internally and see how to integrate this.
