### ISSUE TITLE
Using cloudinary_wordpress with polylang plugin causes error in the site Editor 

### ISSUE THREAD

**Issue by LarsEjaas** [cloudinary/cloudinary_wordpress#894]
## Bug Description

When using cloudinary_wordpress with the Polylang plugin activated, the site Editor is failing.

## Reproducing the bug:

1. install and activate the Cloudinary WordPress Plugin and Polylang (https://wordpress.org/plugins/polylang/)
2. Click on Appearance> Editor in WP Admin.
3. Inspect the error (see screenshot).
The Editor works fine when only one of the plugins is activated.

## Screenshots

![Screenshot 2023-08-12 154058](https://github.com/cloudinary/cloudinary_wordpress/assets/45132430/2af6b043-6519-4764-add9-9402554f97f0)

## Additional context

I get this error in the Editor:

TypeError: Cannot read properties of undefined (reading 'cloudinary/gallery')
    at http://localhost:8080/wp-includes/js/dist/block-editor.min.js?ver=ecf0dc5e749679c4f014:41:157232
    at Array.forEach (<anonymous>)
    at http://localhost:8080/wp-includes/js/dist/block-editor.min.js?ver=ecf0dc5e749679c4f014:41:157201
    at Object.useMemo (http://localhost:8080/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:115389)
    at e.useMemo (http://localhost:8080/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10:9875)
    at iT (http://localhost:8080/wp-includes/js/dist/block-editor.min.js?ver=ecf0dc5e749679c4f014:41:156436)
    at aT (http://localhost:8080/wp-includes/js/dist/block-editor.min.js?ver=ecf0dc5e749679c4f014:41:157431)
    at http://localhost:8080/wp-includes/js/dist/edit-site.min.js?ver=b8d242e1600da32c2411:19:177275
    at Tu (http://localhost:8080/wp-includes/js/dist/edit-site.min.js?ver=b8d242e1600da32c2411:19:177562)
    at kt (http://localhost:8080/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:47633)

## System Report
I have generated the following system report from within the Cloudinary WordPress plugin:

{
    "system_status": {
        "home": "http://localhost:8080",
        "wordpress": "6.3",
        "php": "8.0.29",
        "php_extensions": [
            "Core",
            "date",
            "libxml",
            "openssl",
            "pcre",
            "sqlite3",
            "zlib",
            "ctype",
            "curl",
            "dom",
            "fileinfo",
            "filter",
            "ftp",
            "hash",
            "iconv",
            "json",
            "mbstring",
            "SPL",
            "PDO",
            "pdo_sqlite",
            "session",
            "posix",
            "Reflection",
            "standard",
            "SimpleXML",
            "Phar",
            "tokenizer",
            "xml",
            "xmlreader",
            "xmlwriter",
            "mysqlnd",
            "apache2handler",
            "bcmath",
            "exif",
            "gd",
            "imagick",
            "intl",
            "mysqli",
            "sodium",
            "zip",
            "Zend OPcache"
        ]
    },
    "theme_status": {
        "name": "Frost",
        "version": "1.0.4",
        "author": "WP Engine",
        "author_url": "https://wpengine.com/",
        "child_theme": false
    },
    "plugins_report": {
        "must_use": [],
        "plugins": {
            "polylang/polylang.php": {
                "Name": "Polylang",
                "PluginURI": "https://polylang.pro",
                "Version": "3.4.5",
                "Description": "Adds multilingual capability to WordPress",
                "Author": "WP SYNTEX",
                "AuthorURI": "https://polylang.pro",
                "TextDomain": "polylang",
                "DomainPath": "/languages",
                "Network": false,
                "RequiresWP": "5.8",
                "RequiresPHP": "7.0",
                "UpdateURI": "",
                "Title": "Polylang",
                "AuthorName": "WP SYNTEX",
                "slug": "polylang/polylang.php"
            },
            "cloudinary-image-management-and-manipulation-in-the-cloud-cdn/cloudinary.php": {
                "Name": "Cloudinary",
                "PluginURI": "https://cloudinary.com/documentation/wordpress_integration",
                "Version": "3.1.3",
                "Description": "With the Cloudinary plugin, you can upload and manage your media assets in the cloud, then deliver them to your users through a fast content delivery network, improving your website\u2019s loading speed and overall user experience. Apply multiple transformations and take advantage of a full digital asset management solution without leaving WordPress.",
                "Author": "Cloudinary Ltd., XWP",
                "AuthorURI": "https://cloudinary.com/",
                "TextDomain": "cloudinary",
                "DomainPath": "/languages",
                "Network": false,
                "RequiresWP": "",
                "RequiresPHP": "",
                "UpdateURI": "",
                "Title": "Cloudinary",
                "AuthorName": "Cloudinary Ltd., XWP",
                "slug": "cloudinary-image-management-and-manipulation-in-the-cloud-cdn/cloudinary.php"
            }
        }
    },
    "config_report": {
        "cloudinary_usage": "",
        "cloudinary_last_usage": {
            "plan": "Free",
            "last_updated": "2023-08-11",
            "date_requested": "2023-08-12T00:00:00Z",
            "transformations": {
                "usage": 0,
                "credits_usage": 0
            },
            "objects": {
                "usage": 671
            },
            "bandwidth": {
                "usage": 0,
                "credits_usage": 0
            },
            "storage": {
                "usage": 167052577,
                "credits_usage": 0.16
            },
            "requests": 0,
            "credits": {
                "usage": 0.16,
                "limit": 25,
                "used_percent": 0.64
            },
            "resources": 115,
            "derived_resources": 556,
            "media_limits": {
                "image_max_size_bytes": 10485760,
                "video_max_size_bytes": 104857600,
                "raw_max_size_bytes": 10485760,
                "image_max_px": 25000000,
                "asset_max_total_px": 50000000
            },
            "max_image_size": 10485760,
            "max_video_size": 104857600
        },
        "cloudinary_connection_signature": "",
        "cloudinary_settings_version": "3.1.3",
        "cloudinary_status": "",
        "cloudinary_history": {
            "Free": {
                "05-08-2023": {
                    "plan": "Free",
                    "last_updated": "2023-08-11",
                    "date_requested": "2023-08-05T00:00:00Z",
                    "transformations": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "objects": {
                        "usage": 671
                    },
                    "bandwidth": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "storage": {
                        "usage": 167052577,
                        "credits_usage": 0.16
                    },
                    "requests": 0,
                    "credits": {
                        "usage": 0.16
                    },
                    "resources": 115,
                    "derived_resources": 556,
                    "media_limits": {
                        "image_max_size_bytes": 10485760,
                        "video_max_size_bytes": 104857600,
                        "raw_max_size_bytes": 10485760,
                        "image_max_px": 25000000,
                        "asset_max_total_px": 50000000
                    }
                },
                "06-08-2023": {
                    "plan": "Free",
                    "last_updated": "2023-08-11",
                    "date_requested": "2023-08-06T00:00:00Z",
                    "transformations": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "objects": {
                        "usage": 671
                    },
                    "bandwidth": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "storage": {
                        "usage": 167052577,
                        "credits_usage": 0.16
                    },
                    "requests": 0,
                    "credits": {
                        "usage": 0.16
                    },
                    "resources": 115,
                    "derived_resources": 556,
                    "media_limits": {
                        "image_max_size_bytes": 10485760,
                        "video_max_size_bytes": 104857600,
                        "raw_max_size_bytes": 10485760,
                        "image_max_px": 25000000,
                        "asset_max_total_px": 50000000
                    }
                },
                "07-08-2023": {
                    "plan": "Free",
                    "last_updated": "2023-08-11",
                    "date_requested": "2023-08-07T00:00:00Z",
                    "transformations": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "objects": {
                        "usage": 671
                    },
                    "bandwidth": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "storage": {
                        "usage": 167052577,
                        "credits_usage": 0.16
                    },
                    "requests": 0,
                    "credits": {
                        "usage": 0.16
                    },
                    "resources": 115,
                    "derived_resources": 556,
                    "media_limits": {
                        "image_max_size_bytes": 10485760,
                        "video_max_size_bytes": 104857600,
                        "raw_max_size_bytes": 10485760,
                        "image_max_px": 25000000,
                        "asset_max_total_px": 50000000
                    }
                },
                "08-08-2023": {
                    "plan": "Free",
                    "last_updated": "2023-08-11",
                    "date_requested": "2023-08-08T00:00:00Z",
                    "transformations": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "objects": {
                        "usage": 671
                    },
                    "bandwidth": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "storage": {
                        "usage": 167052577,
                        "credits_usage": 0.16
                    },
                    "requests": 0,
                    "credits": {
                        "usage": 0.16
                    },
                    "resources": 115,
                    "derived_resources": 556,
                    "media_limits": {
                        "image_max_size_bytes": 10485760,
                        "video_max_size_bytes": 104857600,
                        "raw_max_size_bytes": 10485760,
                        "image_max_px": 25000000,
                        "asset_max_total_px": 50000000
                    }
                },
                "09-08-2023": {
                    "plan": "Free",
                    "last_updated": "2023-08-11",
                    "date_requested": "2023-08-09T00:00:00Z",
                    "transformations": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "objects": {
                        "usage": 671
                    },
                    "bandwidth": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "storage": {
                        "usage": 167052577,
                        "credits_usage": 0.16
                    },
                    "requests": 0,
                    "credits": {
                        "usage": 0.16
                    },
                    "resources": 115,
                    "derived_resources": 556,
                    "media_limits": {
                        "image_max_size_bytes": 10485760,
                        "video_max_size_bytes": 104857600,
                        "raw_max_size_bytes": 10485760,
                        "image_max_px": 25000000,
                        "asset_max_total_px": 50000000
                    }
                },
                "10-08-2023": {
                    "plan": "Free",
                    "last_updated": "2023-08-11",
                    "date_requested": "2023-08-10T00:00:00Z",
                    "transformations": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "objects": {
                        "usage": 671
                    },
                    "bandwidth": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "storage": {
                        "usage": 167052577,
                        "credits_usage": 0.16
                    },
                    "requests": 0,
                    "credits": {
                        "usage": 0.16
                    },
                    "resources": 115,
                    "derived_resources": 556,
                    "media_limits": {
                        "image_max_size_bytes": 10485760,
                        "video_max_size_bytes": 104857600,
                        "raw_max_size_bytes": 10485760,
                        "image_max_px": 25000000,
                        "asset_max_total_px": 50000000
                    }
                },
                "11-08-2023": {
                    "plan": "Free",
                    "last_updated": "2023-08-11",
                    "date_requested": "2023-08-11T00:00:00Z",
                    "transformations": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "objects": {
                        "usage": 671
                    },
                    "bandwidth": {
                        "usage": 0,
                        "credits_usage": 0
                    },
                    "storage": {
                        "usage": 167052577,
                        "credits_usage": 0.16
                    },
                    "requests": 0,
                    "credits": {
                        "usage": 0.16
                    },
                    "resources": 115,
                    "derived_resources": 556,
                    "media_limits": {
                        "image_max_size_bytes": 10485760,
                        "video_max_size_bytes": 104857600,
                        "raw_max_size_bytes": 10485760,
                        "image_max_px": 25000000,
                        "asset_max_total_px": 50000000
                    }
                }
            }
        },
        "rest_api_notices": "",
        "sync_media": {
            "auto_sync": "on",
            "cloudinary_folder": "",
            "offload": "dual_full"
        },
        "site_cache": {
            "cache": {
                "enable": "off",
                "cld_purge_all": "",
                "assets": {
                    "plugins": {
                        "enabled": "off",
                        "paths": {
                            "polylang": "",
                            "cloudinary": ""
                        }
                    },
                    "themes": {
                        "enabled": "off",
                        "paths": {
                            "frost": ""
                        }
                    },
                    "wordpress": {
                        "enabled": "off",
                        "paths": {
                            "wp_admin": "",
                            "wp_includes": ""
                        }
                    },
                    "content": {
                        "enabled": "off",
                        "paths": {
                            "wp_content": ""
                        }
                    }
                }
            }
        },
        "additional_domains": {
            "cache_external": {
                "external_assets": "off",
                "uploadable_domains": ""
            }
        },
        "media_display": {
            "image_delivery": "on",
            "image_optimization": "on",
            "image_format": "auto",
            "image_quality": "auto",
            "image_freeform": "",
            "svg_support": "off",
            "crop_sizes": "",
            "image_preview": "https://res.cloudinary.com/demo/image/upload/w_600/sample.jpg",
            "video_delivery": "on",
            "video_player": "wp",
            "video_controls": "on",
            "video_loop": "off",
            "video_autoplay_mode": "off",
            "video_optimization": "on",
            "video_format": "auto",
            "video_quality": "auto",
            "video_freeform": "",
            "video_preview": "",
            "use_lazy_load": "on",
            "lazy_threshold": "100px",
            "lazy_custom_color": "rgba(153,153,153,0.5)",
            "lazy_animate": "on",
            "lazy_placeholder": "blur",
            "dpr": "2X",
            "lazyload_preview": "https://res.cloudinary.com/demo/image/upload/w_600/sample.jpg",
            "enable_breakpoints": "off",
            "pixel_step": 200,
            "breakpoints": "",
            "max_width": 2048,
            "min_width": 200,
            "breakpoints_preview": "https://res.cloudinary.com/demo/image/upload/w_600/sample.jpg"
        },
        "gallery": {
            "transition": "fade",
            "aspectRatio": "3:4",
            "navigation": "always",
            "zoom": true,
            "carouselLocation": "top",
            "carouselOffset": 5,
            "carouselStyle": "thumbnails",
            "displayProps": {
                "mode": "classic",
                "columns": 1
            },
            "indicatorProps": {
                "shape": "round"
            },
            "themeProps": {
                "primary": "#cf2e2e",
                "onPrimary": "#000000",
                "active": "#777777"
            },
            "zoomProps": {
                "type": "popup",
                "viewerPosition": "bottom",
                "trigger": "click"
            },
            "thumbnailProps": {
                "width": 64,
                "height": 64,
                "navigationShape": "radius",
                "selectedStyle": "gradient",
                "selectedBorderPosition": "all",
                "selectedBorderWidth": 4,
                "mediaSymbolShape": "round"
            },
            "cloudName": "headless-image",
            "container": "",
            "queryParam": "AA"
        },
        "cron_system": {
            "cron_system": {
                "enable_cron": "on",
                "tasks": []
            }
        },
        "setup": {
            "reporting": {
                "enable_report": "on"
            }
        },
        "extensions": {
            "media-library": "off"
        }
    },
    "debug_log": [
        "Debug log is empty"
    ]
}

**Comment by Vdeub-cloudinary** [comment]
@LarsEjaas, 
Using Frost (but actually any themes) and Polylang, I get the following error on my own instance:

```
TypeError: Cannot read properties of undefined (reading 'core/separator')
    at https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/block-editor.min.js?ver=ed2b2aa3837336baf00f:41:129592
    at Object.useMemo (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:115389)
    at e.useMemo (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10:9875)
    at JB (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/block-editor.min.js?ver=ed2b2aa3837336baf00f:41:129415)
    at https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/edit-site.min.js?ver=2e1906ed8187c4e2f3f7:12:193747
    at Ri (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/edit-site.min.js?ver=2e1906ed8187c4e2f3f7:12:194047)
    at kt (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:47633)
    at js (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:120746)
    at kl (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88654)
    at yl (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88582)
```

As you can see, this is the same type of error but instead of `cloudinary/gallery`, I have `core/separator`. However, if I disable Cloudinary and leave Polylang alone, the issue **still persists**. As per the stacktrace itself, it is not coming from our plugin but the editor just crashes when going over the array of blocks for you, but in my case, Cloudinary is not even mentioned.
Looking online, I see that Polylang already got this issue: https://wordpress.org/support/topic/polylang-connect-2-3-0-breaks-elementor-3-7-x/ so I'd recommend reaching out to them to fix this.

**Comment by LarsEjaas** [comment]
> @LarsEjaas, Using Frost (but actually any themes) and Polylang, I get the following error on my own instance:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'core/separator')
>     at https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/block-editor.min.js?ver=ed2b2aa3837336baf00f:41:129592
>     at Object.useMemo (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:115389)
>     at e.useMemo (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10:9875)
>     at JB (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/block-editor.min.js?ver=ed2b2aa3837336baf00f:41:129415)
>     at https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/edit-site.min.js?ver=2e1906ed8187c4e2f3f7:12:193747
>     at Ri (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/edit-site.min.js?ver=2e1906ed8187c4e2f3f7:12:194047)
>     at kt (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:47633)
>     at js (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:120746)
>     at kl (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88654)
>     at yl (https://dev-loic-cloudinary-play.pantheonsite.io/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88582)
> ```
> 
> As you can see, this is the same type of error but instead of `cloudinary/gallery`, I have `core/separator`. However, if I disable Cloudinary and leave Polylang alone, the issue **still persists**. As per the stacktrace itself, it is not coming from our plugin but the editor just crashes when going over the array of blocks for you, but in my case, Cloudinary is not even mentioned. Looking online, I see that Polylang already got this issue: https://wordpress.org/support/topic/polylang-connect-2-3-0-breaks-elementor-3-7-x/ so I'd recommend reaching out to them to fix this.

Thanks a lot for the quick reply and taking the time to test this out! I will reach out to the Polylang team instead 🙂

**Comment by LarsEjaas** [comment]
Reaching out to the Polylang team instead!
