### ISSUE TITLE
Cloudinary urls replaced everywhere in the admin but not when accessing acf fields directly

### ISSUE THREAD

**Issue by hlidotbe** [cloudinary/cloudinary_wordpress#900]
## Bug Description

We have a headless setup and extensively use ACF for our websites. When filling a "link" field with a copy/pasted cloudinary url, the url is replaced by the /wp-content/uploads... url in the database. When displayed in the admin the correct url is shown but when using "get_field" we still get the wp-content url instead of the expected cloudinary one. Since storage is set to cloudinary only, it results in errors as the files are not actually available locally.

## Expected Behaviour

Either the url saved in database is what we actually set in the content of the page (prefered) or get_field get_postmeta return the correct url.

## Steps to reproduce

1. Create a page containing ACF fields of type Link
2. Edit the base and set the link to a cloudinary url from the uploaded medias
3. Save the page
4. Call get_field on a link field for this post

## Screenshots

Field as visible in the admin:

<img width="1524" alt="image" src="https://github.com/cloudinary/cloudinary_wordpress/assets/193949/dfe510e7-df8d-46a1-bbba-efdcef5a7e28">

Database Content:

<img width="1299" alt="image" src="https://github.com/cloudinary/cloudinary_wordpress/assets/193949/2c0d7d40-a00a-492a-b67b-cb249cf16d47">

Field as fetch from wp shell:

<img width="866" alt="image" src="https://github.com/cloudinary/cloudinary_wordpress/assets/193949/3ed3c62b-db70-48e3-b723-0784961fdec7">

## Additional context

 - WordPress version: 6.1
 - Plugin version: 3.1.2
 - Gutenberg plugin version (if applicable): /
 - PHP version: 8.0.25
 - Plugin settings: Auto sync, cloudinary only storage, the rest is stock.

**Comment by wissam-khalili** [comment]
Hi there,

Thank you for reaching out.

How do you pull data from the system?  Is it the Rest API, GraqhQL or something else ?

Could you please create a ticket to [support@cloudinary.com](mailto:support@cloudinary.com) with the system report attached as explained [here](https://cloudinary.com/documentation/wordpress_integration#system_report)? Could you also please, before generating the report, make sure that you include images in your report as explained [here](https://cloudinary.com/documentation/wordpress_integration#adding_media_or_posts_pages_to_the_report)?
In case it will be necessary, will you be willing to provide us with temporary access to a sandbox environment of your site where we can take a look and debug if needed?

Thanks,
Wissam

**Comment by hlidotbe** [comment]
We load data through a custom rest route. I've sent a mail with the requested info.
