### ISSUE TITLE
This is failing and returning notice error

### ISSUE THREAD

**Issue by shay-te** [cloudinary/cloudinary_wordpress#933]
Hello this function seems to be broken in our project. 

https://github.com/cloudinary/cloudinary_wordpress/blob/edd640e708893f77002d92c9c83ac8fd82163772/php/class-utils.php#L518

it returns this notice in the start of JSON
```
<br />
<b>Notice</b>:  Uninitialized string offset: 0 in <b>/var/www/html/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-utils.php</b> on line <b>518</b><br />
```

We fixed it like this:

```
         */
        public static function looks_like_json( $thing ) {
//              return ! empty( $thing ) && is_string( $thing ) && in_array( ltrim( $thing )[0], array( '{', '[' ), true );
              if (is_string($thing)) {
                  $trimmedThing = ltrim($thing);
                  return !empty($thing) && strlen($trimmedThing) > 0 && in_array($trimmedThing[0], ['{', '['], true);
              } else {
                  return false; // or handle the case when $thing is not a string
              }
        }
```

**Comment by Vdeub-cloudinary** [comment]
Hi @shay-te, 

Would you mind sharing more context on the issue? Is there a way to reproduce it on our side? 

Could you also share a system report as documented [here](https://support.cloudinary.com/hc/en-us/articles/360022260599-How-to-generate-a-system-report-on-the-WordPress-plugin)?  If you don't want to share it here, please open a ticket to support@cloudinary.com.

Thanks!

**Comment by Vdeub-cloudinary** [comment]
Hi @shay-te, is still relevant? 
Thanks!

**Comment by shay-te** [comment]
No

**Comment by Vdeub-cloudinary** [comment]
Thanks @shay-te !
