### ISSUE TITLE
clean_url method no longer exists in Delivery class

### ISSUE THREAD

**Issue by colis** [cloudinary/cloudinary_wordpress#934]
## Bug Description

Since version `3.1.6` we're getting thousands of PHP warnings due to a couple of calls to the `clean_url()` method that still use the old `Delivery` class and were not renamed to `Utils`

https://github.com/cloudinary/cloudinary_wordpress/blob/edd640e708893f77002d92c9c83ac8fd82163772/php/media/class-filter.php#L399

https://github.com/cloudinary/cloudinary_wordpress/blob/edd640e708893f77002d92c9c83ac8fd82163772/php/class-assets.php#L786

**Comment by Vdeub-cloudinary** [comment]
Hi @colis, 
We are indeed aware of this and the fix is in QA. As for now, you can safely downgrade to `3.1.5` to avoid the issue until we release `3.1.7`.
Hope that makes sense.

**Comment by colis** [comment]
Hi @Vdeub-cloudinary 

sounds good, thanks!
